import axios from "axios";
import crypto from "crypto";

const getCashfreeUrl = () => {
  const env = process.env.CASHFREE_ENV || "sandbox";
  return env === "production"
    ? "https://api.cashfree.com/pg"
    : "https://sandbox.cashfree.com/pg";
};

// Create a configured axios client for Cashfree API requests
export const cashfreeClient = axios.create({
  timeout: 10000, // 10s timeout to prevent hanging requests
});

// Interceptor to attach credentials dynamically per request
cashfreeClient.interceptors.request.use((config) => {
  config.headers = {
    ...config.headers,
    "x-client-id": process.env.CASHFREE_APP_ID,
    "x-client-secret": process.env.CASHFREE_SECRET_KEY,
    "x-api-version": "2023-08-01",
    "Content-Type": "application/json",
  };
  return config;
});

/**
 * Creates a Cashfree order session
 * @param {string} orderId - Unique order ID generated by the backend
 * @param {number} amountInRupees - Total payable amount in Rupees (e.g. 102.36)
 * @param {object} customer - Customer details object { id, phone, email, name }
 * @returns {promise<object>} - Order creation API response containing payment_session_id
 */
export async function createCashfreeOrder(orderId, amountInRupees, customer) {
  const url = `${getCashfreeUrl()}/orders`;
  const appId = process.env.CASHFREE_APP_ID;
  const secretKey = process.env.CASHFREE_SECRET_KEY;

  if (!appId || !secretKey) {
    throw new Error("Cashfree environment variables (CASHFREE_APP_ID or CASHFREE_SECRET_KEY) are not configured.");
  }

  const payload = {
    order_id: orderId,
    order_amount: amountInRupees,
    order_currency: "INR",
    customer_details: {
      customer_id: customer.id.toString(),
      customer_phone: customer.phone,
      customer_email: customer.email || "support@onetimex.in",
      customer_name: customer.name || "Customer",
    },
    order_meta: {
      return_url: process.env.CASHFREE_RETURN_URL || "http://localhost:3000/wallet/status?order_id={order_id}",
      notify_url: process.env.CASHFREE_WEBHOOK_URL,
    },
  };

  const response = await cashfreeClient.post(url, payload);

  return response.data;
}

/**
 * Verifies the Cashfree webhook request signature to prevent payment spoofing.
 * @param {string} signature - x-webhook-signature header value (Base64)
 * @param {string} rawBodyString - Raw request body string
 * @param {string} timestamp - x-webhook-timestamp header value (timestamp in ms)
 * @returns {boolean} - true if signature matches, false otherwise
 */
export function verifyCashfreeSignature(signature, rawBodyString, timestamp) {
  const secretKey = process.env.CASHFREE_SECRET_KEY;
  if (!secretKey) {
    console.error("verifyCashfreeSignature failed: CASHFREE_SECRET_KEY environment variable is not configured.");
    return false;
  }

  if (!signature || !rawBodyString || !timestamp) {
    return false;
  }

  // Concatenate timestamp and raw body as specified by Cashfree documentation
  const data = timestamp + rawBodyString;

  const computedSignature = crypto
    .createHmac("sha256", secretKey)
    .update(data)
    .digest("base64");

  return computedSignature === signature;
}
