// utils/otpCache.js
import { randomInt } from "crypto";
import { valkey } from "../db/valkey.js"; 
import { sendWhatsAppOTP } from "../services/whatsapp.service.js";
import { SENDMAIL } from "../services/mail.services.js";
import ApiError from "./ApiError.js";

const REDIS_KEY_PREFIX = "OTX:otp:"; 
const EMAIL_REDIS_KEY_PREFIX = "OTX:email_otp:";

/**
 * Atomic Compare-and-Delete Lua script for Valkey/Redis:
 * Compares cached OTP with incoming value and deletes key in a single atomic step.
 * Returns 1 on match & successful deletion, 0 otherwise.
 */
const COMPARE_AND_DELETE_LUA = `
  if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('del', KEYS[1])
  else
    return 0
  end
`;

/**
 * Safely removes OTP from Valkey only if it still matches the expected value.
 * Prevents race conditions where a failed older request deletes a newer OTP generated by a concurrent request.
 */
async function deleteOtpIfMatches(key, expectedOtp) {
  if (!key || !expectedOtp) return;
  try {
    await valkey.eval(COMPARE_AND_DELETE_LUA, 1, key, String(expectedOtp).trim());
  } catch (error) {
    console.error("Valkey compare-and-delete error:", error.message);
  }
}

export async function generateAndCacheOtp(phone) { 
  // Generate a cryptographically secure random 6-digit number (100000 to 999999)
  const otp = randomInt(100000, 1000000).toString(); 
  const redisKey = `${REDIS_KEY_PREFIX}${phone}`; 
  
  const EXPIRY_SECONDS = 5 * 60; // 5-minute TTL 

  // 1. Store OTP in your Valkey cache 
  await valkey.set(redisKey, otp, "EX", EXPIRY_SECONDS);

  // 2. Deliver via WhatsApp Business API
  try {
    await sendWhatsAppOTP(phone, otp);
  } catch (whatsappError) {
    console.error("Delivery failure:", whatsappError.message);
    // Delete the cached OTP only if it still matches this failed request's OTP
    await deleteOtpIfMatches(redisKey, otp);
    throw new ApiError(500, `Failed to send OTP via WhatsApp: ${whatsappError.message}`);
  }

  return otp; 
}

/**
 * Generate 6-digit OTP, cache in Valkey (10-min TTL), and send via Nodemailer SMTP
 */
export async function generateAndCacheEmailOtp(email) {
  const cleanEmail = String(email).toLowerCase().trim();
  const otp = randomInt(100000, 1000000).toString();
  const redisKey = `${EMAIL_REDIS_KEY_PREFIX}${cleanEmail}`;
  const EXPIRY_SECONDS = 10 * 60; // 10-minute TTL

  // 1. Store in Valkey cache
  await valkey.set(redisKey, otp, "EX", EXPIRY_SECONDS);

  // 2. Deliver via SMTP
  try {
    const result = await SENDMAIL("EMAIL_OTP", cleanEmail, otp);
    if (!result.success) {
      await deleteOtpIfMatches(redisKey, otp);
      throw new Error(result.error || "SMTP delivery error");
    }
  } catch (error) {
    console.error("Email OTP delivery failure:", error.message);
    await deleteOtpIfMatches(redisKey, otp);
    throw new ApiError(500, `Failed to send verification email: ${error.message}`);
  }

  return otp;
}

export async function verifyOtp(phone, incomingOtp) { 
  if (!phone || !incomingOtp) return false;

  const redisKey = `${REDIS_KEY_PREFIX}${phone}`; 
  try {
    const result = await valkey.eval(
      COMPARE_AND_DELETE_LUA,
      1,
      redisKey,
      String(incomingOtp).trim()
    ); 

    // result === 1 means the OTP matched and was deleted atomically
    return result === 1;
  } catch (error) {
    console.error("Valkey OTP verification error:", error.message);
    return false;
  }
}

export async function verifyEmailOtp(email, incomingOtp) {
  if (!email || !incomingOtp) return false;
  const cleanEmail = String(email).toLowerCase().trim();
  const redisKey = `${EMAIL_REDIS_KEY_PREFIX}${cleanEmail}`;

  try {
    const result = await valkey.eval(
      COMPARE_AND_DELETE_LUA,
      1,
      redisKey,
      String(incomingOtp).trim()
    );
    return result === 1;
  } catch (error) {
    console.error("Valkey Email OTP verification error:", error.message);
    return false;
  }
}